package com.urlshortener.service;

import com.urlshortener.config.AppProperties;
import com.urlshortener.web.error.AliasReservedException;
import com.urlshortener.web.error.InvalidUrlException;
import java.util.Locale;
import java.util.regex.Pattern;
import org.springframework.stereotype.Component;

/**
 * Encapsulates the rules for custom aliases.
 *
 * <p>An alias must:
 * <ul>
 *   <li>Match the configured pattern (default: {@code [A-Za-z0-9_-]{3,32}})</li>
 *   <li>Not equal a reserved path (compared case-insensitively)</li>
 * </ul>
 * Codes generated by {@link ShortCodeGenerator} always satisfy the pattern by
 * construction, so the alias regex doubles as a general "is-a-valid-code"
 * validator that we can share between input validation and route matching.
 */
@Component
public class AliasPolicy {

    private final AppProperties properties;
    private final Pattern aliasPattern;

    public AliasPolicy(AppProperties properties) {
        this.properties = properties;
        this.aliasPattern = Pattern.compile(properties.getAlias().getPattern());
    }

    public void validate(String alias) {
        if (alias == null || alias.isBlank()) {
            throw new InvalidUrlException("Alias must not be blank when provided");
        }
        if (!aliasPattern.matcher(alias).matches()) {
            throw new InvalidUrlException(
                    "Alias must match pattern " + properties.getAlias().getPattern());
        }
        if (isReserved(alias)) {
            throw new AliasReservedException(
                    "Alias '" + alias + "' is a reserved path and cannot be used");
        }
    }

    public boolean isReserved(String alias) {
        String lower = alias.toLowerCase(Locale.ROOT);
        return properties.getReservedPaths().stream()
                .map(p -> p.toLowerCase(Locale.ROOT))
                .anyMatch(lower::equals);
    }
}
